{
    "status": "Invalid", 
    "last_updated": "2011-10-21 12:40:50.279766+00:00", 
    "description": "Testing multi-zone deployment, \"nova boot\" raises the following error with Rev.1439.\nScheduler driver was \"HostFilterScheduler\".\n\n\n2011-08-17 16:05:29,522 ERROR nova [-] Exception during message handling\n(nova): TRACE: Traceback (most recent call last):\n(nova): TRACE:   File \"/root/openstack/nova/nova/rpc/amqp.py\", line 230, in _process_data\n(nova): TRACE:     rval = node_func(context=ctxt, **node_args)\n(nova): TRACE:   File \"/root/openstack/nova/nova/scheduler/manager.py\", line 98, in _schedule\n(nova): TRACE:     **kwargs)\n(nova): TRACE:   File \"/root/openstack/nova/nova/scheduler/zone_aware_scheduler.py\", line 243, in schedule_run_instance\n(nova): TRACE:     request_spec, kwargs)\n(nova): TRACE:   File \"/root/openstack/nova/nova/scheduler/zone_aware_scheduler.py\", line 180, in _provision_resource\n(nova): TRACE:     instance_id, request_spec, kwargs)\n(nova): TRACE:   File \"/root/openstack/nova/nova/scheduler/zone_aware_scheduler.py\", line 166, in _provision_resource_from_blob\n(nova): TRACE:     request_spec, kwargs)\n(nova): TRACE:   File \"/root/openstack/nova/nova/scheduler/zone_aware_scheduler.py\", line 133, in _ask_child_zone_to_create_instance\n(nova): TRACE:     child_blob, reservation_id=reservation_id)\n(nova): TRACE: TypeError: create() got multiple values for keyword argument 'reservation_id'\n(nova): TRACE:", 
    "tags": [], 
    "importance": "Undecided", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/827830", 
    "owner": "https://api.launchpad.net/1.0/~cbehrens", 
    "id": 827830, 
    "index": 3514, 
    "openned": "2011-08-17 07:17:10.968523+00:00", 
    "created": "2011-08-17 07:17:10.968523+00:00", 
    "title": "Fails to boot server with HostFilterScheduler ", 
    "comments": [
        {
            "content": "Testing multi-zone deployment, \"nova boot\" raises the following error with Rev.1439.\nScheduler driver was \"HostFilterScheduler\".\nI guess Servers.create do not receive ipgroups as a parameter in novaclient v1_1.\n\n\n2011-08-17 16:05:29,522 ERROR nova [-] Exception during message handling\n(nova): TRACE: Traceback (most recent call last):\n(nova): TRACE:   File \"/root/openstack/nova/nova/rpc/amqp.py\", line 230, in _process_data\n(nova): TRACE:     rval = node_func(context=ctxt, **node_args)\n(nova): TRACE:   File \"/root/openstack/nova/nova/scheduler/manager.py\", line 98, in _schedule\n(nova): TRACE:     **kwargs)\n(nova): TRACE:   File \"/root/openstack/nova/nova/scheduler/zone_aware_scheduler.py\", line 243, in schedule_run_instance\n(nova): TRACE:     request_spec, kwargs)\n(nova): TRACE:   File \"/root/openstack/nova/nova/scheduler/zone_aware_scheduler.py\", line 180, in _provision_resource\n(nova): TRACE:     instance_id, request_spec, kwargs)\n(nova): TRACE:   File \"/root/openstack/nova/nova/scheduler/zone_aware_scheduler.py\", line 166, in _provision_resource_from_blob\n(nova): TRACE:     request_spec, kwargs)\n(nova): TRACE:   File \"/root/openstack/nova/nova/scheduler/zone_aware_scheduler.py\", line 133, in _ask_child_zone_to_create_instance\n(nova): TRACE:     child_blob, reservation_id=reservation_id)\n(nova): TRACE: TypeError: create() got multiple values for keyword argument 'reservation_id'\n(nova): TRACE:", 
            "date_created": "2011-08-17 07:17:10.968523+00:00", 
            "author": "https://api.launchpad.net/1.0/~hyunsun-moon"
        }, 
        {
            "content": "HostFilterScheduler has gone away since this bug was reported.  Things have been re-factored so that one can specify host filters with any AbstractScheduler descendent.  So, this bug probably needs to be 'Invalid'ated or something.   Related to this, 'nova boot' doesn't work with AbstractSchedulers for a different reason.  I'm fixing this with lp:844160.", 
            "date_created": "2011-09-19 05:21:30.363658+00:00", 
            "author": "https://api.launchpad.net/1.0/~cbehrens"
        }
    ], 
    "closed": "2011-10-21 12:40:49.537909+00:00"
}