{
    "status": "Invalid", 
    "last_updated": "2016-06-02 20:06:09.095576+00:00", 
    "description": "step to reproduce:\nIn python Terminal ,\n>>> from novaclient.v1_1 import client\n>>> ct = client.Client(\"admin\",\"password\",\"admin\",\"http://192.168.1.100:5000/v2.0\")\n>>> ct.hosts.get(\"hostname\")\n\nerror:\nFile \"<stdin>\", line 1, in <module>\n  File \"/opt/stack/python-novaclient/novaclient/v1_1/hosts.py\", line 24, in __repr__\n    return \"<Host: %s>\" % self.host_name\n  File \"/opt/stack/python-novaclient/novaclient/openstack/common/apiclient/base.py\", line 464, in __getattr__\n    raise AttributeError(k)\nAttributeError: host_name", 
    "tags": [
        "api"
    ], 
    "importance": "Undecided", 
    "heat": 8, 
    "link": "https://bugs.launchpad.net/nova/+bug/1327005", 
    "owner": "None", 
    "id": 1327005, 
    "index": 6172, 
    "openned": "2014-06-06 00:41:46.020922+00:00", 
    "created": "2014-06-06 00:41:46.020922+00:00", 
    "title": "Need change host to host_name in host resources", 
    "comments": [
        {
            "content": "step to reproduce:\nIn python Terminal ,\n>>> from novaclient.v1_1 import client\n>>> ct = client.Client(\"admin\",\"password\",\"admin\",\"http://192.168.1.100:5000/v2.0\")\n>>> ct.hosts.get(\"hostname\")\n\nerror:\nFile \"<stdin>\", line 1, in <module>\n  File \"/opt/stack/python-novaclient/novaclient/v1_1/hosts.py\", line 24, in __repr__\n    return \"<Host: %s>\" % self.host_name\n  File \"/opt/stack/python-novaclient/novaclient/openstack/common/apiclient/base.py\", line 464, in __getattr__\n    raise AttributeError(k)\nAttributeError: host_name", 
            "date_created": "2014-06-06 00:41:46.020922+00:00", 
            "author": "https://api.launchpad.net/1.0/~tangmeiyan77"
        }, 
        {
            "content": "This is a python-novaclient bug, not a nova bug", 
            "date_created": "2014-06-23 02:20:47.021137+00:00", 
            "author": "https://api.launchpad.net/1.0/~cyeoh-0"
        }, 
        {
            "content": "In the nova code,\nhttps://github.com/openstack/nova/blob/master/nova/api/openstack/compute/contrib/hosts.py?100#L100\nthere used host_name,\nI think this need to unify, if we change the host to host_name, it also solve this problem. Maybe we can change the python-novaclient to solve this problem, but i think change this bug in nova is much better.\n ", 
            "date_created": "2014-06-23 14:36:42.188432+00:00", 
            "author": "https://api.launchpad.net/1.0/~tangmeiyan77"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/103806", 
            "date_created": "2014-07-01 08:49:32.774710+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/110087", 
            "date_created": "2014-07-28 18:59:47.108849+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/110087\nCommitted: https://git.openstack.org/cgit/openstack/python-novaclient/commit/?id=9ce03a98eb78652fd3480cb0d8323520fd78064c\nSubmitter: Jenkins\nBranch:    master\n\ncommit 9ce03a98eb78652fd3480cb0d8323520fd78064c\nAuthor: melanie witt <email address hidden>\nDate:   Mon Jul 28 18:54:01 2014 +0000\n\n    fix host resource repr to use 'host' attribute\n    \n    This change fixes an AttributeError raised when attempting to\n    represent a host resource as a string.\n    \n    Change-Id: I33369b20ed7f5219c3b507107b8f3a37b46eacee\n    Closes-Bug: #1327005\n", 
            "date_created": "2014-07-31 07:09:53.133260+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Change abandoned by Sean Dague (<email address hidden>) on branch: master\nReview: https://review.openstack.org/103806\nReason: This review is > 4 weeks without comment, and failed Jenkins the last time it was checked. We are abandoning this for now. Feel free to reactivate the review by pressing the restore button and leaving a 'recheck' comment to get fresh test results.", 
            "date_created": "2014-11-20 15:25:17.012249+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Removing \"In Progress\" status and assignee as change is abandoned.\n", 
            "date_created": "2015-02-12 16:35:55.451175+00:00", 
            "author": "https://api.launchpad.net/1.0/~dims-v"
        }, 
        {
            "content": "per comment #1, mark this invalid", 
            "date_created": "2016-06-02 20:06:08.321012+00:00", 
            "author": "https://api.launchpad.net/1.0/~jichenjc"
        }
    ], 
    "closed": "2016-06-02 20:05:29.738994+00:00"
}