{
    "status": "Confirmed", 
    "last_updated": "2017-08-03 07:20:08.442263+00:00", 
    "description": "In my test, found when in import image, config drive image maybe failed and throw ImageBusy exception\n\nThis often occured in nova host-evacuate test scenario.\nIn order to get vm ha, when compute node down, we need evacuate all instances from this node to the other.\nhow to reproduce:\n1. create 50 instances with config driver disk in node1\n2. unplug the ceph network cable of this node\n3. do host-evacuate for this node\n4. watch all the instances status, maybe failed because of this bug\n\nI think, it is because the config driver disk still in use in ceph, so we need to caputure the ImageBusy exception and add retry logic", 
    "tags": [], 
    "importance": "Undecided", 
    "heat": 18, 
    "link": "https://bugs.launchpad.net/nova/+bug/1628448", 
    "owner": "None", 
    "id": 1628448, 
    "index": 7725, 
    "openned": "2016-09-28 10:12:27.905607+00:00", 
    "created": "2016-09-28 10:12:27.905607+00:00", 
    "title": "Remove_image maybe throw ImageBusy exception", 
    "comments": [
        {
            "content": "In my test, found when in import image, config drive image maybe failed and throw ImageBusy exception", 
            "date_created": "2016-09-28 10:12:27.905607+00:00", 
            "author": "https://api.launchpad.net/1.0/~coolias-lj"
        }, 
        {
            "content": "my patch: https://review.openstack.org/#/c/378501/", 
            "date_created": "2016-09-29 02:45:29.080253+00:00", 
            "author": "https://api.launchpad.net/1.0/~coolias-lj"
        }, 
        {
            "content": "Change abandoned by Michael Still (<email address hidden>) on branch: master\nReview: https://review.openstack.org/378501\nReason: This patch has been sitting unchanged for more than 12 weeks. I am therefore going to abandon it to keep the review queue sane. Please feel free to restore the change if you're still working on it.", 
            "date_created": "2016-12-24 08:53:47.914155+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "\nThere are no currently open reviews on this bug, changing\nthe status back to the previous state and unassigning. If\nthere are active reviews related to this bug, please include\nlinks in comments.\n", 
            "date_created": "2017-06-23 12:47:50.059072+00:00", 
            "author": "https://api.launchpad.net/1.0/~sdague"
        }, 
        {
            "content": "I found the same problem in my mitaka version. It dose not happen every time. So I feel that maybe the connection between config drive is not disconnected from instance, it shows busy status.", 
            "date_created": "2017-08-03 07:20:07.598078+00:00", 
            "author": "https://api.launchpad.net/1.0/~zhuhq"
        }
    ]
}