{
    "status": "Fix Released", 
    "last_updated": "2016-09-01 13:19:08.974542+00:00", 
    "description": "Im' runnign openstack mitaka on a 3 node installation (controller, compute and network).  I installed it first under ubuntu 14.04  and later under ubuntu 16.04, but both have the same error when I try to launch an instance.\n\nThe error I get is the same using horizon or the command \"nova boot --image cirros --flavor 1 --nic net-name=test erste\".\n\nErrormessage from the command line is \nERROR (ClientException): Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.\n<class 'oslo_config.cfg.NoSuchOptError'> (HTTP 500) (Request-ID: req-2c2bb960-feb8-45ed-a3d1-65b8833d9228)\n\nI'm using the versions below:\n dpkg -l | grep nova\nii  nova-api                             2:13.0.0-0ubuntu5                     all          OpenStack Compute - API frontend\nii  nova-common                          2:13.0.0-0ubuntu5                     all          OpenStack Compute - common files\nii  nova-conductor                       2:13.0.0-0ubuntu5                     all          OpenStack Compute - conductor service\nii  nova-consoleauth                     2:13.0.0-0ubuntu5                     all          OpenStack Compute - Console Authenticator\nii  nova-novncproxy                      2:13.0.0-0ubuntu5                     all          OpenStack Compute - NoVNC proxy\nii  nova-scheduler                       2:13.0.0-0ubuntu5                     all          OpenStack Compute - virtual machine scheduler\nii  python-nova                          2:13.0.0-0ubuntu5                     all          OpenStack Compute Python libraries\nii  python-novaclient                    2:3.3.1-2                             all          client library for OpenStack Compute API - Python 2.7", 
    "tags": [
        "in-stable-mitaka", 
        "low-hanging-fruit", 
        "mitaka-backport-potential"
    ], 
    "importance": "Medium", 
    "heat": 18, 
    "link": "https://bugs.launchpad.net/nova/+bug/1604428", 
    "owner": "https://api.launchpad.net/1.0/~ryanx-seldon", 
    "id": 1604428, 
    "index": 4584, 
    "created": "2016-07-19 13:47:18.107579+00:00", 
    "title": "NoSuchOptError: no such option in group neutron: auth_plugin", 
    "comments": [
        {
            "content": "Im' runnign openstack mitaka on a 3 node installation (controller, compute and network).  I installed it first under ubuntu 14.04  and later under ubuntu 16.04, but both have the same error when I try to launch an instance.\n\nThe error I get is the same using horizon or the command \"nova boot --image cirros --flavor 1 --nic net-name=test erste\".\n\nErrormessage from the command line is \nERROR (ClientException): Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.\n<class 'oslo_config.cfg.NoSuchOptError'> (HTTP 500) (Request-ID: req-2c2bb960-feb8-45ed-a3d1-65b8833d9228)\n\nI'm using the versions below:\n dpkg -l | grep nova\nii  nova-api                             2:13.0.0-0ubuntu5                     all          OpenStack Compute - API frontend\nii  nova-common                          2:13.0.0-0ubuntu5                     all          OpenStack Compute - common files\nii  nova-conductor                       2:13.0.0-0ubuntu5                     all          OpenStack Compute - conductor service\nii  nova-consoleauth                     2:13.0.0-0ubuntu5                     all          OpenStack Compute - Console Authenticator\nii  nova-novncproxy                      2:13.0.0-0ubuntu5                     all          OpenStack Compute - NoVNC proxy\nii  nova-scheduler                       2:13.0.0-0ubuntu5                     all          OpenStack Compute - virtual machine scheduler\nii  python-nova                          2:13.0.0-0ubuntu5                     all          OpenStack Compute Python libraries\nii  python-novaclient                    2:3.3.1-2                             all          client library for OpenStack Compute API - Python 2.7", 
            "date_created": "2016-07-19 13:47:18.107579+00:00", 
            "author": "https://api.launchpad.net/1.0/~mvdv95"
        }, 
        {
            "content": "", 
            "date_created": "2016-07-19 13:47:18.107579+00:00", 
            "author": "https://api.launchpad.net/1.0/~mvdv95"
        }, 
        {
            "content": "That's the same like bug 1574988 which got resolved with [1] in Newton but not backported to Mitaka or Liberty.\n\nReferences:\n[1] https://git.openstack.org/cgit/openstack/nova/commit/?id=2647f91ae97844a73176fc1c8663d9b186bdec1a", 
            "date_created": "2016-07-19 15:29:57.457276+00:00", 
            "author": "https://api.launchpad.net/1.0/~mzoeller"
        }, 
        {
            "content": "Does this mean I need to upgrade to Newton to get it resolved?  Is Newton already stable and available to use?", 
            "date_created": "2016-07-19 16:37:30.844877+00:00", 
            "author": "https://api.launchpad.net/1.0/~mvdv95"
        }, 
        {
            "content": "I will try and get the fix that was included in newton backported to Mitaka, which means you wouldn't have to updgrade.", 
            "date_created": "2016-07-19 16:42:03.798517+00:00", 
            "author": "https://api.launchpad.net/1.0/~ryanx-seldon"
        }, 
        {
            "content": "Ok, thanks wil you le me know when  this is done and how to install this fix, or is this done automatically?  Sorry for the questions, but I'm rather new at using openstack.", 
            "date_created": "2016-07-19 16:52:41.237039+00:00", 
            "author": "https://api.launchpad.net/1.0/~mvdv95"
        }, 
        {
            "content": "Fix proposed to branch: stable/mitaka\nReview: https://review.openstack.org/344371", 
            "date_created": "2016-07-19 17:04:38.090427+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Marc,\n\nThe patch proposed above will this problem, you just need to wait for it to be merged. Once it is merged to the mitaka branch, then you can re-download the new code for mitaka and you should be good.", 
            "date_created": "2016-07-19 17:07:20.902932+00:00", 
            "author": "https://api.launchpad.net/1.0/~ryanx-seldon"
        }, 
        {
            "content": "Hello Ryan,\n\nsorry again for the maybe stupid question, but how do I \"redownload the new\ncode for Mitaka\" to install the patch?\n\nRegards,\nMarc\n\nOn Tue, Jul 19, 2016 at 7:07 PM, Ryan Selden <email address hidden> wrote:\n\n> Marc,\n>\n> The patch proposed above will this problem, you just need to wait for it\n> to be merged. Once it is merged to the mitaka branch, then you can re-\n> download the new code for mitaka and you should be good.\n>\n> --\n> You received this bug notification because you are subscribed to the bug\n> report.\n> https://bugs.launchpad.net/bugs/1604428\n>\n> Title:\n>   NoSuchOptError: no such option in group neutron: auth_plugin\n>\n> Status in OpenStack Compute (nova):\n>   In Progress\n>\n> Bug description:\n>   Im' runnign openstack mitaka on a 3 node installation (controller,\n>   compute and network).  I installed it first under ubuntu 14.04  and\n>   later under ubuntu 16.04, but both have the same error when I try to\n>   launch an instance.\n>\n>   The error I get is the same using horizon or the command \"nova boot\n>   --image cirros --flavor 1 --nic net-name=test erste\".\n>\n>   Errormessage from the command line is\n>   ERROR (ClientException): Unexpected API Error. Please report this at\n> http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.\n>   <class 'oslo_config.cfg.NoSuchOptError'> (HTTP 500) (Request-ID:\n> req-2c2bb960-feb8-45ed-a3d1-65b8833d9228)\n>\n>   I'm using the versions below:\n>    dpkg -l | grep nova\n>   ii  nova-api                             2:13.0.0-0ubuntu5\n>        all          OpenStack Compute - API frontend\n>   ii  nova-common                          2:13.0.0-0ubuntu5\n>        all          OpenStack Compute - common files\n>   ii  nova-conductor                       2:13.0.0-0ubuntu5\n>        all          OpenStack Compute - conductor service\n>   ii  nova-consoleauth                     2:13.0.0-0ubuntu5\n>        all          OpenStack Compute - Console Authenticator\n>   ii  nova-novncproxy                      2:13.0.0-0ubuntu5\n>        all          OpenStack Compute - NoVNC proxy\n>   ii  nova-scheduler                       2:13.0.0-0ubuntu5\n>        all          OpenStack Compute - virtual machine scheduler\n>   ii  python-nova                          2:13.0.0-0ubuntu5\n>        all          OpenStack Compute Python libraries\n>   ii  python-novaclient                    2:3.3.1-2\n>        all          client library for OpenStack Compute API - Python 2.7\n>\n> To manage notifications about this bug go to:\n> https://bugs.launchpad.net/nova/+bug/1604428/+subscriptions\n>\n", 
            "date_created": "2016-07-20 08:33:16+00:00", 
            "author": "https://api.launchpad.net/1.0/~mvdv95"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/344371\nCommitted: https://git.openstack.org/cgit/openstack/nova/commit/?id=32a9d01c80ba13dd1321aef33073ad5a0b146fda\nSubmitter: Jenkins\nBranch:    stable/mitaka\n\ncommit 32a9d01c80ba13dd1321aef33073ad5a0b146fda\nAuthor: Wenzhi Yu <wenzhi_yu@163.com>\nDate:   Tue Apr 26 18:55:16 2016 +0800\n\n    Fix NoSuchOptError when referring to conf.neutron.auth_plugin\n    \n    Backporting to Mitaka\n    \n    We already replaced 'auth_plugin' with 'auth_type'[1], now an\n    oslo_config.cfg.NoSuchOptError will be threw up when referring to\n    conf.neutron.auth_plugin.\n    \n    This commit replace the usage of conf.neutron.auth_plugin by\n    conf.neutron.auth_type.\n    \n    [1]https://github.com/openstack/keystoneauth/commit/a56ed4218aef5a2e528aa682cea967e767dca923\n    \n    Change-Id: I0b72f278ba8e28508274079ff284042fb9ea3d64\n    Closes-Bug: #1574988\n    Closes-Bug: #1604428\n    (cherry picked from commit 2647f91ae97844a73176fc1c8663d9b186bdec1a)\n", 
            "date_created": "2016-08-03 04:22:47.133942+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "This issue was fixed in the openstack/nova 13.1.1 release.", 
            "date_created": "2016-08-09 18:25:17.918895+00:00", 
            "author": "https://api.launchpad.net/1.0/~doug-hellmann"
        }, 
        {
            "content": "That was a Mitaka bug only as the bug in Newton got fixed with bug 1574988", 
            "date_created": "2016-08-11 15:08:22.126797+00:00", 
            "author": "https://api.launchpad.net/1.0/~mzoeller"
        }, 
        {
            "content": "Hello,\n\nI belive I managed to download the tar.gz file for nova 13.1.1, but cna you help me how to install it?  Sorry for the basic question, but I'm new to openstack.\n\nRegards,\nMarc", 
            "date_created": "2016-09-01 09:03:05.846382+00:00", 
            "author": "https://api.launchpad.net/1.0/~mvdv95"
        }, 
        {
            "content": "Hello,\n\nI figured out how to install it and I cna launch my instance now so don't bother about my previous question.\n\nThansk to all how helped to get this fix in Mitaka :-).\n\nRegards,\nMarc", 
            "date_created": "2016-09-01 13:19:07.674167+00:00", 
            "author": "https://api.launchpad.net/1.0/~mvdv95"
        }
    ]
}