{
    "status": "Fix Released", 
    "last_updated": "2013-04-04 11:00:48.342161+00:00", 
    "description": "Description:\n------------------\n\nError message thrown while Creating Flavor with duplicate Flavor ID i.e Flavor ID that already exists is not proper.\n\nEnvironment:\n--------------\nFolsom\n\nActual Error Message:\n------------------------\n\nMessage from API:\"message\": \"Instance Type PS_flavor_2 already exists.\"\nMessage from Python Client: ERROR: Instance Type ps_abd already exists. (HTTP 409) (Request-ID: req-b8f6821a-51c2-46a7-bd09-6b4896afd6f4)\n\nExpected Error Message:\n----------------------------\nShould be something like(When Flavor ID is X)\n\n\"message\": \"Flavor with ID X already exists.\"\n\nPython Nova client output:\n------------------------------\n\nrajalakshmi_ganesan@ubuntu:~$ nova flavor-list\n+-----+-----------+-----------+------+-----------+------+-------+-------------+-----------+-------------+\n| ID  | Name      | Memory_MB | Disk | Ephemeral | Swap | VCPUs | RXTX_Factor | Is_Public | extra_specs |\n+-----+-----------+-----------+------+-----------+------+-------+-------------+-----------+-------------+\n| 1   | m1.tiny   | 512       | 0    | 0         |      | 1     | 1.0         | True      | {}          |\n| 2   | m1.small  | 2048      | 20   | 0         |      | 1     | 1.0         | True      | {}          |\n| 3   | m1.medium | 4096      | 40   | 0         |      | 2     | 1.0         | True      | {}          |\n| 4   | m1.large  | 8192      | 80   | 0         |      | 4     | 1.0         | True      | {}          |\n| 5   | m1.xlarge | 16384     | 160  | 0         |      | 8     | 1.0         | True      | {}          |\n| 12  | flavor-12 | 1024      | 10   | 2         | 512  | 2     | 1.0         | True      | {}          |\n| 333 | PS_flavor | 1024      | 10   | 2         | 22   | 2     | 2.0         | True      | {}          |\n+-----+-----------+-----------+------+-----------+------+-------+-------------+-----------+-------------+\nrajalakshmi_ganesan@ubuntu:~$ nova flavor-create ps_abd 333 22 22 22\nERROR: Instance Type ps_abd already exists. (HTTP 409) (Request-ID: req-417f6ed5-72c9-4eef-85e5-cff067931f6e)\nrajalakshmi_ganesan@ubuntu:~$\n\nCURL COMMAND OUTPUTS:\n--------------------------------\n\nrajalakshmi_ganesan@ubuntu:~$ nova flavor-list\n+-----+-----------+-----------+------+-----------+------+-------+-------------+-----------+-------------+\n| ID  | Name      | Memory_MB | Disk | Ephemeral | Swap | VCPUs | RXTX_Factor | Is_Public | extra_specs |\n+-----+-----------+-----------+------+-----------+------+-------+-------------+-----------+-------------+\n| 1   | m1.tiny   | 512       | 0    | 0         |      | 1     | 1.0         | True      | {}          |\n| 2   | m1.small  | 2048      | 20   | 0         |      | 1     | 1.0         | True      | {}          |\n| 3   | m1.medium | 4096      | 40   | 0         |      | 2     | 1.0         | True      | {}          |\n| 4   | m1.large  | 8192      | 80   | 0         |      | 4     | 1.0         | True      | {}          |\n| 5   | m1.xlarge | 16384     | 160  | 0         |      | 8     | 1.0         | True      | {}          |\n| 12  | flavor-12 | 1024      | 10   | 2         | 512  | 2     | 1.0         | True      | {}          |\n| 333 | PS_flavor | 1024      | 10   | 2         | 22   | 2     | 2.0         | True      | {}          |\n+-----+-----------+-----------+------+-----------+------+-------+-------------+-----------+-------------+\nrajalakshmi_ganesan@ubuntu:~$ curl -i http://15.184.64.226:8774/v2/25ecbf309f7748c6a173fabf2a673a65/flavors -X POST -H \"X-Auth-Project-Id: admin\" -H \"User-Agent: python-novaclient\" -H \"Content-Type: application/json\" -H \"X-Auth-Token: 0b78256729a848559f7a9a45e24ef554\" -d '{\"flavor\": {\"disk\": 10, \"vcpus\": 2, \"ram\": 1024, \"name\": \"PS_flavor_2\", \"id\": 333, \"swap\": 22, \"os-flavor-access:is_public\": true, \"rxtx_factor\": 2, \"OS-FLV-EXT-DATA:ephemeral\": 2}}'\nHTTP/1.1 409 Conflict\nContent-Length: 93\nContent-Type: application/json; charset=UTF-8\nX-Compute-Request-Id: req-08da768b-29bc-4444-8b8d-4ea3111caab7\nDate: Wed, 26 Sep 2012 14:48:35 GMT\n\n{\"conflictingRequest\": {\"message\": \"Instance Type PS_flavor_2 already exists.\", \"code\": 409}}rajalakshmi_ganesan@ubuntu:~$", 
    "tags": [], 
    "importance": "Undecided", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/1056918", 
    "owner": "https://api.launchpad.net/1.0/~andrew-mccrae", 
    "id": 1056918, 
    "index": 3120, 
    "created": "2012-09-26 14:57:00.133513+00:00", 
    "title": "Folsom - Error message for 'Create Flavor'  when Flavor ID is duplicate is not proper", 
    "comments": [
        {
            "content": "Description:\n------------------\n\nError message thrown while Creating Flavor with duplicate Flavor ID i.e Flavor ID that already exists is not proper.\n\nEnvironment:\n--------------\nFolsom\n\nActual Error Message:\n------------------------\n\n\"message\": \"Instance Type PS_flavor_2 already exists.\"\n\nExpected Error Message:\n----------------------------\nShould be something like(When Flavor ID is X)\n\n\"message\": \"Flavor with ID X already exists.\"\n\nCURL COMMAND OUTPUTS:\n--------------------------------\n\nrajalakshmi_ganesan@ubuntu:~$ nova flavor-list\n+-----+-----------+-----------+------+-----------+------+-------+-------------+-----------+-------------+\n| ID  | Name      | Memory_MB | Disk | Ephemeral | Swap | VCPUs | RXTX_Factor | Is_Public | extra_specs |\n+-----+-----------+-----------+------+-----------+------+-------+-------------+-----------+-------------+\n| 1   | m1.tiny   | 512       | 0    | 0         |      | 1     | 1.0         | True      | {}          |\n| 2   | m1.small  | 2048      | 20   | 0         |      | 1     | 1.0         | True      | {}          |\n| 3   | m1.medium | 4096      | 40   | 0         |      | 2     | 1.0         | True      | {}          |\n| 4   | m1.large  | 8192      | 80   | 0         |      | 4     | 1.0         | True      | {}          |\n| 5   | m1.xlarge | 16384     | 160  | 0         |      | 8     | 1.0         | True      | {}          |\n| 12  | flavor-12 | 1024      | 10   | 2         | 512  | 2     | 1.0         | True      | {}          |\n| 333 | PS_flavor | 1024      | 10   | 2         | 22   | 2     | 2.0         | True      | {}          |\n+-----+-----------+-----------+------+-----------+------+-------+-------------+-----------+-------------+\nrajalakshmi_ganesan@ubuntu:~$ curl -i http://15.184.64.226:8774/v2/25ecbf309f7748c6a173fabf2a673a65/flavors -X POST -H \"X-Auth-Project-Id: admin\" -H \"User-Agent: python-novaclient\" -H \"Content-Type: application/json\" -H \"X-Auth-Token: 0b78256729a848559f7a9a45e24ef554\" -d '{\"flavor\": {\"disk\": 10, \"vcpus\": 2, \"ram\": 1024, \"name\": \"PS_flavor_2\", \"id\": 333, \"swap\": 22, \"os-flavor-access:is_public\": true, \"rxtx_factor\": 2, \"OS-FLV-EXT-DATA:ephemeral\": 2}}'\nHTTP/1.1 409 Conflict\nContent-Length: 93\nContent-Type: application/json; charset=UTF-8\nX-Compute-Request-Id: req-08da768b-29bc-4444-8b8d-4ea3111caab7\nDate: Wed, 26 Sep 2012 14:48:35 GMT\n\n{\"conflictingRequest\": {\"message\": \"Instance Type PS_flavor_2 already exists.\", \"code\": 409}}rajalakshmi_ganesan@ubuntu:~$", 
            "date_created": "2012-09-26 14:57:00.133513+00:00", 
            "author": "https://api.launchpad.net/1.0/~rajalakshmi-ganesan"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/13751", 
            "date_created": "2012-09-27 12:18:31.655092+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/13751\nCommitted: http://github.com/openstack/nova/commit/3db7a943bebbda5fea07fc80813cabc436fb892b\nSubmitter: Jenkins\nBranch:    master\n\ncommit 3db7a943bebbda5fea07fc80813cabc436fb892b\nAuthor: Andy McCrae <email address hidden>\nDate:   Thu Sep 27 11:58:14 2012 +0000\n\n    Fixes error message for flavor-create duplicate ID\n    \n    Fixes bug 1056918\n    \n    Change-Id: I516153211504b67f6e8b8ebb138abcef4be4d73e\n", 
            "date_created": "2012-09-30 07:36:42.699541+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "From what I've seen - this is now fixed, the python-novaclient is unaffected, marking that as Invalid.", 
            "date_created": "2012-10-01 08:00:00.821667+00:00", 
            "author": "https://api.launchpad.net/1.0/~andrew-mccrae"
        }
    ]
}